[[main]]
name = "記事"
pageRef = "/posts"
weight = 10

[[main]]
name = "Writeup"
pageRef = "/writeups"
weight = 20

[[main]]
name = "本サイトについて"
pageRef = "/about"
weight = 30

[[footer]]
name = "免責事項"
pageRef = "/disclaimer"
weight = 10