enableSearch = true

copyright = "Â© { year } kazutamu"

disableImageOptimization = false

disableImageZoom = false

[params]
  mainSections = ["posts"]

[homepage]
  layout = "background"
  homepageImage = "images/kazutamu_001.JPG"
  showRecent = true
  recentLimit = 5
  cardView = true
  layoutBackgroundBlur = true

[footer]
showThemeAttribution = false

[article]
showTableOfContents = true
showWordCount = false
showReadingTime = false