enableSearch = true

copyright = "Â© { year } kazutamu"

disableImageOptimization = true

disableImageZoom = false

defaultBackgroundImage = "img/kazutamu_001.JPG"

defaultFeaturedImage = "img/kazutamu_001.JPG"

[params]
  mainSections = ["posts"]

[homepage]
  layout = "background"
  showRecent = true
  recentLimit = 5
  cardView = true
  layoutBackgroundBlur = true

[footer]
showThemeAttribution = false

[article]
showTableOfContents = true
showWordCount = false
showReadingTime = false