enableSearch = true

copyright = "Â© { year } kazutamu"

disableImageOptimization = true

disableImageZoom = false

defaultBackgroundImage = "img/kazutamu_001.JPG"

colorScheme = "Blowfish"



[params]
  mainSections = ["posts"]

[announcement]
  enable = true
  text = "ğŸš§ ã‚µã‚¤ãƒˆæ§‹ç¯‰ä¸­ã§ã™ï¼ˆä¸€éƒ¨ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã¯é †æ¬¡å…¬é–‹äºˆå®šï¼‰"


[homepage]
  layout = "hero"
  showRecent = true
  recentLimit = 5
  layoutBackgroundBlur = true

[footer]
showThemeAttribution = false

[article]
  showDate = true
  showWordCount = false
  showReadingTime = false
  showTaxonomies = true