baseURL = 'https://www.kazutamu.com/'
languageCode = 'en-us'
title = 'KAZUTAMU'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[params]
  mainSections = ["posts", "writeups"]
  ShowBreadCrumbs = false
  ShowPostNavLinks = false

[params.cover]
image = "/images/kazutamu_001.JPG"
alt = "kazutamu"
caption = ""
relative = false
hidden = false

[params.homeInfoParams]
Title = "KAZUTAMU"
Content = "心躍るセキュリティ"

[params.footer]
  text = '[免責事項](/disclaimer/)'

