baseURL = 'https://www.kazutamu.com/'
languageCode = 'en-us'
title = 'KAZUTAMU'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[params]
  mainSections = ["posts", "writeups"]

[params.homeInfoParams]
Title = "Kazutamu"
Content = "心躍るセキュリティ"

[params.footer]
  text = '[免責事項](/disclaimer/)'

