baseURL = 'https://www.kazutamu.com/'
defaultContentLanguage = "ja"
languageCode = 'ja-jp'
title = 'KAZUTAMU'
theme = 'blowfish'
enableRobotsTXT = true


[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
